[build]
  publish = "website"

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/portfolio.html"
  status = 200

[[redirects]]
  from = "/investment"
  to = "/investment.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/journal"
  to = "/journal.html"
  status = 200

[[redirects]]
  from = "/planning-guide"
  to = "/planning-guide.html"
  status = 200
